name = "qbyten-web"
compatibility_date = "2024-05-01"

[vars]
# Set this in Cloudflare Pages (Project Settings → Environment Variables)
# ADMIN_TOKEN = "your-strong-token"

[[d1_databases]]
binding = "DB"
database_name = "qbyten"
database_id = "LOCAL"

